### ISSUE TITLE
Is there any sample code?

### ISSUE THREAD

**Issue by cnstephen** [jopanel/solana-php-sdk#1]
Is there any sample code? For example: get the price of ca, get the profit and loss percentage of a certain ca held by the account, and monitor the buying and selling of ca after buying ca. Examples like this

**Comment by cnstephen** [comment]
thanks@！

**Comment by jopanel** [comment]
Hi
This API SDK is a PHP version of the Solana API: [https://solana.com/docs/rpc](https://solana.com/docs/rpc)

Check out the sample code in the wiki: [https://github.com/jopanel/solana-php-sdk/wiki/Documentation](https://github.com/jopanel/solana-php-sdk/wiki/Documentation)

You mentioned a few items:

- Get the price of ca 
Solana does not track fiat currency and price of token at a dex/cex.

- get the profit and loss percentage of a certain ca held by the account
You would have to use this SDK to get transactions of a wallet, track amounts traded, and then you would be on your own to track the value. Check out the Raydium API I built as well, if the token is on the Raydium dex you can convert a mint address to a USD price.

- monitor the buying and selling of ca after buying ca
I built out the webhooks that solana offers where you could webhook track a specific account. You could also create a cron job and run the API calls on wallets.

Try telling ChatGPT to visit my wiki document and write code for you. It does okay, but you will need to do your own research on what you want to do.
